# Generated by Django 5.2.1 on 2025-05-15 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Себестоимость')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена продажи')),
                ('category', models.CharField(choices=[('conditioner', 'Кондиционер'), ('installation', 'Монтаж'), ('dismantling', 'Демонтаж'), ('maintenance', 'Обслуживание'), ('additional', 'Доп услуга')], max_length=15, verbose_name='Категория')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
    ]
